name: Generate Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Documentation
        uses: andstor/jsdoc-action@v1.2.0
        with:
          # build docs from /source
          source_dir: ./source
          recurse: true
          template: minami
          # docs generated in VM but not in repo 
          output_dir: ./docs/jsdocs
          
        #TODO: add file to local repo
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.0.0
        with:
          add: './docs/jsdocs'
          message: 'automatically updated documentation' 
