# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: cd source ; npm ci ; npm run build --if-present ; npm test
